name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=ciceronkeith4-code&show_icons=true&hide_border=true&theme=transparent
          path: stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=ciceronkeith4-code&layout=compact&langs_count=6&hide_border=true&theme=transparent
          path: top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit stats
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update GitHub stats"
          add: "stats.svg top-langs.svg"
